### ISSUE TITLE
 xctest client proxy error with: Error: connect ECONNREFUSED 

### ISSUE THREAD

**Issue by lylh** [xudafeng/app-inspector#4]
>> inspector start at: http://100.84.252.213:5678
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
>> proxy.js:58:18 [master] pid:33338 xctest client proxy error with: Error: connect ECONNREFUSED 100.84.230.241:8100
/usr/local/lib/node_modules/app-inspector/node_modules/xlogger/lib/xlogger.js:169
  throw new Error(res);
  ^

Error: >> proxy.js:58:18 [master] pid:33338 xctest client proxy error with: Error: connect ECONNREFUSED 100.84.230.241:8100
    at Logger.error (/usr/local/lib/node_modules/app-inspector/node_modules/xlogger/lib/xlogger.js:169:9)
    at Request._callback (/usr/local/lib/node_modules/app-inspector/node_modules/xctest-client/lib/proxy.js:58:18)
    at self.callback (/usr/local/lib/node_modules/app-inspector/node_modules/xctest-client/node_modules/request/request.js:199:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/usr/local/lib/node_modules/app-inspector/node_modules/xctest-client/node_modules/request/request.js:821:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:256:9)
    at emitOne (events.js:77:13)``

**Comment by xudafeng** [comment]
@lylh `macaca doctor`

**Comment by lylh** [comment]
@xudafeng
```
Node.js checklist:

  node env: /usr/local/bin/node
  node version: v4.4.1

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy

  Android checklist:

  JAVA version is `1.8.0_51`
  JAVA_HOME is not set
  ANDROID_HOME is not set

  Installed driver list:

  ios: 1.0.30

```

**Comment by xudafeng** [comment]
@lylh 使用模拟器看下

**Comment by lylh** [comment]
@xudafeng  web端一直在loading...中

**Comment by xudafeng** [comment]
@lylh 什么模拟器？ip5？

**Comment by lylh** [comment]
@xudafeng  ip 5s 固件9.3

**Comment by xudafeng** [comment]
@lylh 真机可能这样，模拟器不会的

**Comment by lylh** [comment]
@xudafeng  模拟现在是一直loading   ip 5s 固件9.3  发现是webDriver一直没有启动起来，启动就自动退出了

**Comment by xudafeng** [comment]
@lylh qq 群287162474
